# Generated by Django 2.0.4 on 2018-04-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
