# Generated by Django 2.0.4 on 2018-04-22 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180422_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка')),
            ],
            options={
                'verbose_name_plural': 'Факультеты',
                'verbose_name': 'Факультет',
            },
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': 'Кафедра', 'verbose_name_plural': 'Кафедра'},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='theme',
            new_name='specialization',
        ),
        migrations.AddField(
            model_name='specialization',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Department', verbose_name='Факультет'),
            preserve_default=False,
        ),
    ]
