# Generated by Django 2.0.4 on 2018-04-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180424_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.IntegerField(choices=[(1, 'Шаблон работы'), (2, 'Методичекие указания'), (3, 'Видеофайл'), (4, 'Домашнее задание')], default=1, verbose_name='Тип файла'),
            preserve_default=False,
        ),
    ]
