# Generated by Django 2.0.5 on 2018-06-03 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20180508_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDiscipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Учебный блок',
                'verbose_name_plural': 'Файлы',
                'ordering': ('course__title', 'title'),
            },
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('title',), 'verbose_name': 'Учебная дисциплина', 'verbose_name_plural': 'Учебные дисциплины'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('course_discipline__title', 'title'), 'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'ordering': ('title',), 'verbose_name': 'Кафедра', 'verbose_name_plural': 'Кафедра'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ('title',), 'verbose_name': 'Тип файла', 'verbose_name_plural': 'Типы файлов'},
        ),
        migrations.RemoveField(
            model_name='document',
            name='course',
        ),
        migrations.AddField(
            model_name='coursediscipline',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Course'),
        ),
        migrations.AddField(
            model_name='document',
            name='course_discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.CourseDiscipline', verbose_name='Предмет'),
        ),
    ]
